# The contents of this file are generated. See site_config.yml.
theme: minima
bool: true
number: 12334
array: [a, b, c, d]
multi-line-array:
  - value 1
  - value 2
null-value: null
undefined_value:
date: 2022-07-01
symbol: 😊
name: __MSG_@appName__
short_name: __MSG_appShortName_
manifest_version: 3
version: 23.1.21
description: __MSG_appDesc__
homepage: https://justiceo.github.io/xtension
author: Justice Ogbonna
license: MIT
keywords:
  [chrome, firefox, opera, safari, addon, extension, starter, boilerplate]
homepage_url: https://github.com/justiceo/xtension
icons:
  16: assets/logo-16x16.png
  32: assets/logo-32x32.png
  48: assets/logo-48x48.png
  128: assets/logo-128x128.png
bugs:
funding:
repository:
  type: git
  url: https://github.com/justiceo/xtension
